/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author MICHAEL
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoCreaTuCuenta = new javax.swing.JLabel();
        jButtonRegresarInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextConstrasenia = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        fondoVenom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1037, 746));
        getContentPane().setLayout(null);

        fondoCreaTuCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crea_cuenta.jpg"))); // NOI18N
        getContentPane().add(fondoCreaTuCuenta);
        fondoCreaTuCuenta.setBounds(170, 0, 715, 223);

        jButtonRegresarInicio.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRegresarInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegresarInicio.setForeground(new java.awt.Color(0, 204, 204));
        jButtonRegresarInicio.setText("Inicio");
        jButtonRegresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarInicio);
        jButtonRegresarInicio.setBounds(20, 20, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NOMBRES:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 290, 90, 30);

        jTextNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextNombres);
        jTextNombres.setBounds(500, 290, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("APELLIDOS:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 340, 100, 30);

        jTextApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextApellidos);
        jTextApellidos.setBounds(500, 340, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("NOMBRE-USUARIO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 390, 160, 30);

        jTextNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextNombreUsuario);
        jTextNombreUsuario.setBounds(500, 390, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("CONSTRASEÑA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 440, 130, 30);

        jTextConstrasenia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextConstrasenia);
        jTextConstrasenia.setBounds(500, 440, 240, 30);

        jButtonCrear.setBackground(new java.awt.Color(51, 204, 255));
        jButtonCrear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("CREAR CUENTA");
        getContentPane().add(jButtonCrear);
        jButtonCrear.setBounds(410, 550, 200, 40);

        fondoVenom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoVenom.png"))); // NOI18N
        getContentPane().add(fondoVenom);
        fondoVenom.setBounds(0, 0, 1037, 746);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarInicioActionPerformed
        dispose();
        IniciarSesion c = new IniciarSesion();
        c.setVisible(true); 
    }//GEN-LAST:event_jButtonRegresarInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoCreaTuCuenta;
    private javax.swing.JLabel fondoVenom;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonRegresarInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextConstrasenia;
    private javax.swing.JTextField jTextNombreUsuario;
    private javax.swing.JTextField jTextNombres;
    // End of variables declaration//GEN-END:variables
}
